apiVersion: v1
kind: Service
metadata:
  name: service-one
  labels:
    app: service-one
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: service-one