apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-servicetwo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: service-two
    spec:
      containers:
      - name: service-two
        image: service-two:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082