apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-servicetwo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-two
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: service-two
    spec:
      containers:
      - name: service-two
        image: service-two:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        volumeMounts:
          - name: service-two-config
            mountPath: "/config"
      volumes:
      - name: service-two-config
        configMap:
          name: my-config
          items:
            - key: service-two-config.properties
              path: service-two-config.properties